# Generated by Django 5.0.6 on 2026-07-02 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название цвета')),
                ('finish_type', models.CharField(choices=[('weave', 'Плетение'), ('cushion', 'Подушки'), ('frame', 'Каркас')], max_length=16, verbose_name='Тип отделки')),
                ('hex', models.CharField(default='#cccccc', help_text='Например #3b3a36 — для образца и базового цвета 3D-модели', max_length=7, verbose_name='HEX-цвет')),
                ('swatch_image', models.ImageField(blank=True, help_text='Необязательно — если задан, показывается вместо однотонного образца', null=True, upload_to='colors/', verbose_name='Образец текстуры')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Цвет отделки',
                'verbose_name_plural': 'Цвета отделки',
                'ordering': ['finish_type', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота, см'),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина, см'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, help_text='Материалы в модели должны называться weave / cushion / frame', null=True, upload_to='models/', verbose_name='3D-модель (.glb)'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_3d_poster',
            field=models.ImageField(blank=True, null=True, upload_to='models/posters/', verbose_name='Постер 3D-модели'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес, кг'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина, см'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.coloroption', verbose_name='Доступные цвета'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('unit_price', models.IntegerField(help_text='Снимок цены на момент заявки', verbose_name='Цена за штуку')),
                ('selected_colors', models.JSONField(blank=True, default=dict, help_text='Снимок вида {"Плетение": "Графит", "Подушки": "Беж"}', verbose_name='Выбранные цвета')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.product')),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявки',
            },
        ),
    ]
